MODEL:
  BACKBONE:
    MODEL_NAME: "resnext101_32x8d"
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  ATSS:
    NUM_CLASSES: 6  # the number of classes including background
    ANCHOR_SIZES: (64, 128, 256, 512, 1024) # 8S
    ASPECT_RATIOS: (1.0,)
    SCALES_PER_OCTAVE: 1
    USE_DCN_IN_TOWER: False
    TOPK: 9 # topk for selecting candidate positive samples from each level
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.01
  NUM_GPUS: 2
  IMS_PER_BATCH: 16
